export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";


export const DATE_SENT = "DATE_SENT";


export const PROJECT_CREATED = "PROJECT_CREATED";
export const TASK_CREATED = "TASK_CREATED";
export const GET_PROJECTS = "GET_PROJECTS";
export const PROJECT_DELETED = "PROJECT_DELETED";
export const TASK_DELETED = "TASK_DELETED";
export const TASK_EDITED = "TASK_EDITED";
export const TASK_DUPLICATED = "TASK_DUPLICATED";
export const USERS_COMMENT = "USERS_COMMENT";